### Alligator analysis
rm(list = ls())

### load required packages
library(rjags)
library(RInSp)
library(MCMCpack)
library(loo)

### set working directory
setwd("~/AlligatorData")

### load data

AlligatorAll  <- read.csv("data/AlligatorData_S4.csv")

### make data into data matrix

AlligatorMat  <- data.matrix(AlligatorAll)

### Alligator individuals nested within site and sex

### Define the model and save as a .txt file

sink("multinom.dir.hier.txt")
cat("
    data{
    for (i in 1:N) {
    nisk[i]  <- sum(yisk[i,1:J]) # calculate the number of prey observed for each predator
    }
    }
    model {
    for (i in 1:N) {
    yisk[i, 1:J] ~ dmulti(pisk[i,1:J], nisk[i]) # individual observations used to estimate preferences pisk
    pisk[i, 1:J] ~ ddirch(alphask[sex[i],pop[i], 1:J]) # pisk distributed dirichlet with vector alphask
    }
    for (s in 1:S) {
    for (k in 1:K) {
    for (j in 1:J) {
    alphask[s,k,j]  <- qsk[s,k,j] * wsk[s,k] + 0.05 # define each component of the vector alphask where each term is composed of a preference qsk and a concentration parameter wsk
    }
    }
    }
    for (s in 1:S) {
    for (k in 1:K) {
    qsk[s,k, 1:J] ~ddirch(alphak[k, 1:J]) # qsk is distributed Dirichlet with vector alphak
    }
    }
    for (k in 1:K) {
    for (j in 1:J) {
    alphak[k,j]  <- qk[k,j] * wk[k] + 0.05 # define alphak components with population preferences and concentration parameter for the population
    }
    }
    for (k in 1:K) {
    qk[k, 1:J] ~ ddirch(alphapop[1:J]) # site preferences qk are distributed Dirichlet with vector alphapop
    }
    for (j in 1:J) {
    alphapop[j]  <- q[j] * w + 0.05 # alphapop is defined by the population preference q and concentration parameter w
    }
    q[1:J] ~ ddirch(alpha[]) # set priors for q using vector alpha
    for (j in 1:J){
    alpha[j]  <- 1 # vector of 1's leads to a uniform distribution
    }
    for (s in 1:S) {
    for (k in 1:K) {
    wsk[s,k] ~ dunif(0, 30) # uniform prior for wsk
    }
    }
    for (k in 1:K) {
    wk[k] ~ dunif(0, 30) # uniform prior for wk
    }
    w ~ dunif(0.1, 30) # uniform prior for w
    for (i in 1:N){
    for(j in 1:J){
    diff.prop[i,j]  <- abs(pisk[i, j] - qsk[sex[i],pop[i],j]) # estimate PSi comparing individuals diets to average diet for individuals of the same sex and site
    }
    PS[i]  <- 1 - 0.5 * sum(diff.prop[i,1:J])
    }
    mean.PS  <- mean(PS[]) # calculate mean PS for each iteration
    # calculate log likelihood for each data point at each iteration for calculating waic
    for (i in 1:N){
      log_lik[i] <- logdensity.dirch(pisk[i,], alphask[sex[i], pop[i], ])
    }
    }
    ", fill = TRUE)
sink()

### set up data for analysis

data  <- list(yisk = AlligatorMat[,2:10], N = as.numeric(length(AlligatorMat[,1])), J = 9, K = 19, S = 2,
              pop = AlligatorMat[,1], sex = AlligatorMat[,11])

### set up initial value function for q and w
### all other initial values will be randomly generated by JAGS
RowTotal  <- apply(AlligatorMat[,3:11], 1, sum)

Props  <- as.numeric(apply(AlligatorMat[,3:11], 2, function(x){sum(x)/sum(RowTotal)}))
inits  <- function(){list(q = Props, w = (1))}

### Initialize model running three chains with a burn in period of 100000 iterations. This can take a while
jags <- jags.model("multinom.dir.hier.txt", data = data,
                   n.chains = 3, n.adapt = 100000, inits = inits )

### list of parameters to estimate from the model
params  <- c("pisk", "wsk", "wk", "qsk", "qk", "w", "q", "PS", "mean.PS", "log_lik")

### sample 2000 times from the posterior distribution of the parameters sampling every 100 iterations
samples  <- jags.samples(jags, variable.names = params, n.iter = 2000,
                         n.thin = 100)

### create matrix of log-likelihoods to calculate waic
### matrix is SxN with S being the number of simulations and N being the number of observations in the model

log_lik_mat <- t(cbind(samples$log_lik[,,1], samples$log_lik[,,2], samples$log_lik[,,3]))

### use package 'loo' to calculate WAIC

SiteSexWAIC <- waic(log_lik_mat)

### Calculate DIC for the model if preferred over WAIC

AlligatorSiteSexDIC <- dic.samples(jags, 1000, n.thin = 100, type = "pD")

### Alternative model -- Alligators nested in Site only

sink("multinom.dir.hier.txt")
cat("
    data{
    for (i in 1:N) {
    nik[i]  <- sum(yik[i,1:J]) # calculate the sample size for each individual
    }
    }
    model {
    for (i in 1:N) {
    yik[i, 1:J] ~ dmulti(pik[i, 1:J], nik[i]) # individual observations used to estimate preferences pik
    pik[i, 1:J] ~ ddirch(alphak[pop[i], 1:J] ) # each individual's preferences are drawn from a dirichlet distribution with vector alphak
    }
    for(k in 1:K) {
    for(j in 1:J) {
    alphak[k,j]  <- pk[k, j] * wk[k] + 0.05 # components of alphak are defined by site level preference pk and concentration parameter wk
    }
    }
    for (k in 1:K) {
    pk[k, 1:J] ~ ddirch(alphapop[1:J]) # site level preferences are distributed Dirichlet with vector alphapop
    }
    for(j in 1:J) {
    alphapop[j]  <- q[j] * w +0.05 # components of alphapop are defined by the population preference q and the concentration parameter w
    }
    q[1:J]  ~ ddirch(alpha[]) # define the prior for q
    for (j in 1:J) {
    alpha[j]  <- 1 # vector of 1's gives uniform prior for q
    }
    for (k in 1:K) {
    wk[k] ~ dunif(0, 20) # difine the prior for wk's
    }
    w ~ dunif(0,30) #define the prior for w
    for (i in 1:N){
    for(j in 1:J){
    diff.prop[i,j]  <- abs(pik[i, j] - pk[pop[i],j]) #estimate PSi
    }
    PS[i]  <- 1 - 0.5 * sum(diff.prop[i,1:J])
    }
    mean.PS  <- mean(PS[]) #estimate mean PSi for each iteration
    for (i in 1:N){
      log_lik[i] <- logdensity.dirch(pik[i, ], alphak[pop[i], ])
    }
    }
    ", fill = TRUE)
sink()

### define data for jags
data  <- list(yik = AlligatorMat[,2:10], N = as.numeric(length(AlligatorMat[,1])), J = 9, K = 19,
              pop = AlligatorMat[,1])

### set up initial value functions for q and w.
### other initial values will be randomly selected by JAGS
RowTotal  <- apply(AlligatorMat[,3:11], 1, sum)

Props  <- as.numeric(apply(AlligatorMat[,3:11], 2, function(x){sum(x)/sum(RowTotal)}))
inits  <- function(){list(q = Props, w = (1))}

### initialize model with three chains and a burn-in period of 100000 iterations
jags2 <- jags.model("multinom.dir.hier.txt", data = data,
                    n.chains = 3, n.adapt = 100000, inits = inits )

### define parameters to be sampled
params  <- c("pik", "wk", "w", "q", "PS", "mean.PS", "log_lik")

### sample 2000 times from the posterior distribution of the parameters sampling every 100 iterations
samples2  <- jags.samples(jags2, variable.names = params, n.iter = 2000,
                          n.thin = 100)

### create matrix of log-likelihoods to calculate waic
### matrix is SxN with S being the number of simulations and N being the number of observations in the model

log_lik_mat2 <- t(cbind(samples2$log_lik[,,1], samples2$log_lik[,,2], samples2$log_lik[,,3]))

### use package 'loo' to calculate waic

AlligatorSiteWAIC <- waic(log_lik_mat2)

### Calculate DIC, if preferred over WAIC

AlligatorSiteDIC <- dic.samples(jags2, 1000, n.thin = 100, type = "pD")

### Alligators nested only within population

sink("multinom.dir.hier.txt")
cat("
    data{
    for (i in 1:N) {
    ni[i]  <- sum(yi[i,1:J]) # calculate sample size for each individual
    }
    }
    model {
    for (i in 1:N) {
    yi[i, 1:J] ~ dmulti(pi[i, 1:J], ni[i]) # individual observations used to estimate preferences pi
    pi[i, 1:J] ~ ddirch(alphapop[1:J] ) # individual preferences distributed Dirichlet with vector alphapop
    }
    for(j in 1:J) {
    alphapop[j]  <- q[j] * w +0.05 # components of alphapop are defined by the population prefence q and the concentration parameter w
    }
    q[1:J]  ~ ddirch(alpha[]) # define priors for q
    for (j in 1:J) {
    alpha[j]  <- 1 # a vector of 1's defines a uniform distribution
    }
    w ~ dunif(0,30) # define a prior for w
    for (i in 1:N){
    for(j in 1:J){
    diff.prop[i,j]  <- abs(pi[i, j] - q[j]) # calculate PSi
    }
    PS[i]  <- 1 - 0.5 * sum(diff.prop[i,1:J])
    }
    mean.PS  <- mean(PS[]) # calculate the mean PS for each iteration
    for (i in 1:N){
      log_lik[i] <- logdensity.dirch(pi[i,], alphapop[])
    }
    }
    ", fill = TRUE)
sink()

### define data for JAGS
data  <- list(yi = AlligatorAll[,2:10], N = as.numeric(length(AlligatorAll[,1])), J = 9)

### create initial values functions for q and w
### all other parameters will be given random initial values by JAGS
RowTotal  <- apply(AlligatorMat[,2:10], 1, sum)

Props  <- as.numeric(apply(AlligatorMat[,2:10], 2, function(x){sum(x)/sum(RowTotal)}))
inits  <- function(){list(q = Props, w = (1))}

### Initiate model using three chains and a burn-in period of 100000
jags3 <- jags.model("multinom.dir.hier.txt", data = data,
                    n.chains = 3, n.adapt = 100000, inits = inits )

### define parameters to sample
params  <- c("pi", "w", "q", "PS", "mean.PS", "log_lik")

### sample 2000 times from the posterior distribution of the parameters sampling every 100 iterations
samples3  <- jags.samples(jags3, variable.names = params, n.iter = 2000,
                          n.thin = 100)

### create matrix of log-likelihoods to calculate waic
### matrix is SxN with S being the number of simulations and N being the number of observations in the model

log_lik_mat3 <- t(cbind(samples3$log_lik[,,1], samples3$log_lik[,,2], samples3$log_lik[,,3]))

### use package 'loo' to calculate waic

AlligatorWAIC <- waic(log_lik_mat3)

### Calculate DIC values
AlligatorDIC <-  dic.samples(jags3, 1000, n.thin = 100, type = "pD")

